- name: Create node exporter user
  ansible.builtin.user:
    name: nodeexp
    system: yes
    shell: /usr/sbin/nologin

- name: Download node exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract node exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install node exporter binary
  ansible.builtin.copy:
    src: /tmp/node_exporter-1.8.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: "0755"
    remote_src: yes

- name: Start node exporter
  ansible.builtin.shell: |
    pgrep node_exporter || nohup node_exporter > /var/log/node_exporter.log 2>&1 &