all:
  vars:
    ansible_host: "{{ lookup('env', 'ANSIBLE_TARGET_HOST') | default('127.0.0.1', true) }}"
    ansible_port: "{{ lookup('env', 'ANSIBLE_TARGET_PORT') | default('2222', true) }}"
    ansible_user: "{{ lookup('env', 'ANSIBLE_TARGET_USER') | default('ansible', true) }}"
    ansible_password: "{{ lookup('env', 'ANSIBLE_TARGET_PASS') | default('ansible', true) }}"
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  children:
    monitoring:
      hosts:
        docker-target: