name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Lint
        run: npm run lint
        working-directory: ./app

      - name: Test
        run: npm test
        working-directory: ./app

      - name: Build Docker image
        run: |
          IMAGE_NAME=node_app
          SHA=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:$SHA ./app

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          IMAGE_NAME=node_app
          SHA=${GITHUB_SHA::7}
          docker tag $IMAGE_NAME:$SHA ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$SHA
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$SHA